name: Warscapes

packages:
  - server/**
  - common/**
  - "app/**"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
  server:
    run: dart server/bin/server.dart

  build:
    exec: dart run build_runner build --delete-conflicting-outputs
  
    