name: Warscapes

packages:
  - server/**
  - shared/**
  - "*"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
  server:
    run: dart server/bin/server.dart
  
    