name: warscapes
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.2.0
  flame_forge2d: ^0.12.0
  hooks_riverpod: ^1.0.4
  web_socket_channel: ^2.2.0
  http: ^0.13.4
  freezed_annotation: ^2.1.0
  warscapes_api:
    path: ./warscapes_api
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/animations/