name: server
description: A server app using the shelf package and Docker.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  redis: ^3.1.0
  shelf: ^1.0.0
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.2
  uuid: ^3.0.6
  web_socket_channel: ^2.2.0
  warscapes_api: 
    path: ../warscapes_api

dev_dependencies:
  build_runner: ^2.0.0
  http: ^0.13.0
  lints: ^1.0.0
  shelf_router_generator: ^1.0.3
  test: ^1.15.7
  test_process: ^2.0.0
