name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  shelf: ^1.0.0
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.2
  uuid: ^3.0.6
  web_socket_channel: ^2.2.0
  vector_math: ^2.1.2
  redis: ^3.1.0
  riverpod: ^2.1.1

  common: 
    git: 
      url: https://github.com/garysm/warscapes.git
      path: common/
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.0.0
  http: ^0.13.0
  lints: ^1.0.0
  shelf_router_generator: ^1.0.3
  test: ^1.15.7
  test_process: ^2.0.0
