name: common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none' 


environment:
  sdk: '>=2.17.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  vector_math: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1